### ISSUE TITLE
Yum and dnf ansible modules not working under centos:8

### ISSUE THREAD

**Issue by distorhead** [werf/werf#1983]
```
[DEBUG] OUTPUT LINE: │ │ ┌ Building stage install
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  ┌ yum 'Install a package using yum with dnf'
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │ stderr:
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   Traceback (most recent call last):
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "/usr/lib64/python3.6/site-packages/libdnf/conf.py", line 14, in swig_import_helper
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │       return importlib.import_module(mname)
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │       return _bootstrap._gcd_import(name[level:], package, level)
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "<frozen importlib._bootstrap>", line 571, in module_from_spec
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "<frozen importlib._bootstrap_external>", line 922, in create_module
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   ImportError: libnss3.so: cannot open shared object file: No such file or directory
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   During handling of the above exception, another exception occurred:
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   Traceback (most recent call last):
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "/usr/bin/dnf", line 57, in <module>
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │       from dnf.cli import main
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "/usr/lib/python3.6/site-packages/dnf/__init__.py", line 30, in <module>
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │       import dnf.base
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "/usr/lib/python3.6/site-packages/dnf/base.py", line 29, in <module>
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │       import libdnf.transaction
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "/usr/lib64/python3.6/site-packages/libdnf/__init__.py", line 3, in <module>
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │       from . import conf
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "/usr/lib64/python3.6/site-packages/libdnf/conf.py", line 17, in <module>
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │       _conf = swig_import_helper()
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "/usr/lib64/python3.6/site-packages/libdnf/conf.py", line 16, in swig_import_helper
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │       return importlib.import_module('_conf')
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │       return _bootstrap._gcd_import(name[level:], package, level)
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   ModuleNotFoundError: No module named '_conf'
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │ Traceback (most recent call last):
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "/usr/lib64/python3.6/site-packages/libdnf/conf.py", line 14, in swig_import_helper
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     return importlib.import_module(mname)
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     return _bootstrap._gcd_import(name[level:], package, level)
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "<frozen importlib._bootstrap>", line 571, in module_from_spec
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "<frozen importlib._bootstrap_external>", line 922, in create_module
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │ ImportError: libnss3.so: cannot open shared object file: No such file or directory
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │ 
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │ During handling of the above exception, another exception occurred:
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │ 
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │ Traceback (most recent call last):
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "/usr/bin/dnf", line 57, in <module>
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     from dnf.cli import main
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "/usr/lib/python3.6/site-packages/dnf/__init__.py", line 30, in <module>
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     import dnf.base
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "/usr/lib/python3.6/site-packages/dnf/base.py", line 29, in <module>
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     import libdnf.transaction
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "/usr/lib64/python3.6/site-packages/libdnf/__init__.py", line 3, in <module>
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     from . import conf
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "/usr/lib64/python3.6/site-packages/libdnf/conf.py", line 17, in <module>
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     _conf = swig_import_helper()
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "/usr/lib64/python3.6/site-packages/libdnf/conf.py", line 16, in swig_import_helper
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     return importlib.import_module('_conf')
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │     return _bootstrap._gcd_import(name[level:], package, level)
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │ ModuleNotFoundError: No module named '_conf'
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  │ exit code: 1
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  └ yum 'Install a package using yum with dnf' (1.52 seconds) FAILED
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  Failed task configuration:
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install      name: Install a package using yum with dnf
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install      yum:
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install        name: httpd
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install        state: latest
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  /tmp/werf-config-render-078819611
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install       4  image: centos-8
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install       5  from: centos:8
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install       6  ansible:
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install       7    install:
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install       8    - name: "Install a package using yum with dnf"
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install       9      yum:
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install      10        name: httpd
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install      11        state: latest
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install      12  
[DEBUG] OUTPUT LINE: │ │ │ centos-8/install  
```

**Comment by distorhead** [comment]
Future steps:
 - build stapel with python3;
 - update ansible to 2.9.

So there will be 2 options:
1. ansible 2.9 + python 3
2. legacy (default) ansible 2.7 + python 2

User should have an ability to choose ansible version.

python3+new ansible should fix the issue.

**Comment by alexey-igrychev** [comment]
This issue is being closed because the ansible functionality is no longer being developed or supported. This feature has been deprecated and will be removed in version v3. We recommend using the shell directive instead.
