### ISSUE TITLE
werf crashed

### ISSUE THREAD

**Issue by n-bes** [werf/werf#2822]
I ran two parallel command
```
DOCKER_BUILDKIT=0 werf build # crashed, stacktrace below
DOCKER_BUILDKIT=1 werf build
```
werf version: ```v1.1.21+fix29```
stages storage: ```:local```

Stacktrace:
```
│ │ dockerfile  Successfully built 7f441c3e30ca
│ │ dockerfile  Successfully tagged a1be8993-daa1-44df-982f-f94177cf9d7c:latest
│ │ Discarding newly built image for stage dockerfile by signature 625ca47bfd8b8b494b75f6038ab15ed56fb4f902e8f9ee4473315203:        ↵
│ │ detected already existing image                                                                                                                  ↵
│ │ -------------------------------:625ca47bfd8b8b494b75f6038ab15ed56fb4f902e8f9ee4473315203-1603826729094 in the stages  ↵
│ │ storage


panic: interface conversion: container_runtime.ImageInterface is nil, not *container_runtime.StageImage

goroutine 1 [running]:
github.com/werf/werf/pkg/build.(*BuildPhase).atomicBuildStageImage(0xc000d68b00, 0xc0005a0160, 0x2b572a0, 0xc000678ae0, 0x0, 0x0)
    /home/ubuntu/actions-runner/_work/werf/werf/pkg/build/build_phase.go:396 +0x1ad6
github.com/werf/werf/pkg/build.(*BuildPhase).buildStage.func2(0x100000003f5e801, 0xc00d8c8160)
    /home/ubuntu/actions-runner/_work/werf/werf/pkg/build/build_phase.go:339 +0x188
github.com/werf/logboek.logProcess.func1(0x22f29a0, 0xc00d8c8160)
    /home/ubuntu/go/pkg/mod/github.com/werf/logboek@v0.3.5-0.20200608145450-5b5f18fe7009/process.go:285 +0x26
github.com/werf/logboek.logProcess(0xc0008b6330, 0x2a, 0x0, 0xc00d8c08c0, 0x0, 0xc00000c100, 0x0, 0xc00d8a5230, 0xc0008b6301, 0xc00d8a5230)
    /home/ubuntu/go/pkg/mod/github.com/werf/logboek@v0.3.5-0.20200608145450-5b5f18fe7009/process.go:292 +0x10d
github.com/werf/logboek.LogProcess(0xc0008b6330, 0x2a, 0x0, 0xc00d8c08c0, 0x0, 0xc00000c100, 0x0, 0xc00d8a5230, 0xc000e4acf0, 0xc00d820340)
    /home/ubuntu/go/pkg/mod/github.com/werf/logboek@v0.3.5-0.20200608145450-5b5f18fe7009/process.go:263 +0x78
github.com/werf/logboek.Level.LogProcess(...)
    /home/ubuntu/go/pkg/mod/github.com/werf/logboek@v0.3.5-0.20200608145450-5b5f18fe7009/level.go:93
github.com/werf/werf/pkg/build.(*BuildPhase).buildStage(0xc000d68b00, 0xc0005a0160, 0x2b572a0, 0xc000678ae0, 0x0, 0x0)
    /home/ubuntu/actions-runner/_work/werf/werf/pkg/build/build_phase.go:328 +0x30b
github.com/werf/werf/pkg/build.(*BuildPhase).onImageStage(0xc000d68b00, 0xc0005a0160, 0x2b572a0, 0xc000678ae0, 0x216dc00, 0x2a94120, 0xc00000e018)
    /home/ubuntu/actions-runner/_work/werf/werf/pkg/build/build_phase.go:183 +0x505
github.com/werf/werf/pkg/build.(*BuildPhase).OnImageStage.func1(0xc0005a0160, 0x2b572a0, 0xc000678ae0, 0xc000c5ef00, 0x2, 0x2)
    /home/ubuntu/actions-runner/_work/werf/werf/pkg/build/build_phase.go:126 +0x51
github.com/werf/werf/pkg/build.(*StagesIterator).OnImageStage(0xc000d68c40, 0xc0005a0160, 0x2b572a0, 0xc000678ae0, 0xc000c5f010, 0x10, 0x216dcc0)
    /home/ubuntu/actions-runner/_work/werf/werf/pkg/build/stages_iterator.go:55 +0x333
github.com/werf/werf/pkg/build.(*BuildPhase).OnImageStage(0xc000d68b00, 0xc0005a0160, 0x2b572a0, 0xc000678ae0, 0x3, 0x3)
    /home/ubuntu/actions-runner/_work/werf/werf/pkg/build/build_phase.go:125 +0x74
github.com/werf/werf/pkg/build.(*Conveyor).runPhases.func2(0x3f5e801, 0xc000d12420)
    /home/ubuntu/actions-runner/_work/werf/werf/pkg/build/conveyor.go:485 +0x274
github.com/werf/logboek.logProcess.func1(0x22f29a0, 0xc000d12420)
    /home/ubuntu/go/pkg/mod/github.com/werf/logboek@v0.3.5-0.20200608145450-5b5f18fe7009/process.go:285 +0x26
github.com/werf/logboek.logProcess(0xc000dabaa0, 0x1a, 0x0, 0x0, 0x0, 0xc000ae5a00, 0x0, 0xc0002a0390, 0x216ed01, 0xc0002a0390)
    /home/ubuntu/go/pkg/mod/github.com/werf/logboek@v0.3.5-0.20200608145450-5b5f18fe7009/process.go:292 +0x10d
github.com/werf/logboek.LogProcess(0xc000dabaa0, 0x1a, 0x0, 0x0, 0x0, 0xc000ae5a00, 0x0, 0xc0002a0390, 0xc000c28240, 0x38)
    /home/ubuntu/go/pkg/mod/github.com/werf/logboek@v0.3.5-0.20200608145450-5b5f18fe7009/process.go:263 +0x78
github.com/werf/logboek.Level.LogProcess(...)
    /home/ubuntu/go/pkg/mod/github.com/werf/logboek@v0.3.5-0.20200608145450-5b5f18fe7009/level.go:93
github.com/werf/werf/pkg/build.(*Conveyor).runPhases(0xc0000ec140, 0xc000d121f0, 0x1, 0x1, 0xc0003f2b01, 0x0, 0x0)
    /home/ubuntu/actions-runner/_work/werf/werf/pkg/build/conveyor.go:471 +0x59b
github.com/werf/werf/pkg/build.(*Conveyor).BuildStages(0xc0000ec140, 0x24c0000, 0x0, 0x0, 0x0, 0xc0000ec140, 0x0)
    /home/ubuntu/actions-runner/_work/werf/werf/pkg/build/conveyor.go:317 +0x108
github.com/werf/werf/cmd/werf/stages/build/cmd_factory.runStagesBuild.func2(0xc0000ec140, 0x2b, 0xc0006ca660)
    /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/stages/build/cmd_factory/main.go:211 +0x57
github.com/werf/werf/pkg/build.(*ConveyorWithRetryWrapper).WithRetryBlock.func1(0xc0000ec140, 0xc000d39988, 0x0, 0x0, 0x0)
    /home/ubuntu/actions-runner/_work/werf/werf/pkg/build/conveyor_with_retry.go:64 +0x84
github.com/werf/werf/pkg/build.(*ConveyorWithRetryWrapper).WithRetryBlock(0xc000e4ba10, 0xc000e4b988, 0x0, 0x0)
    /home/ubuntu/actions-runner/_work/werf/werf/pkg/build/conveyor_with_retry.go:72 +0x1ac
github.com/werf/werf/cmd/werf/stages/build/cmd_factory.runStagesBuild(0x3f940e0, 0x3f965a0, 0x3fc43b8, 0x0, 0x0, 0x0, 0x0)
    /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/stages/build/cmd_factory/main.go:210 +0xbb3
github.com/werf/werf/cmd/werf/stages/build/cmd_factory.NewCmdWithData.func1.1(0xbfde36ff002e540a, 0x4bc0844)
    /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/stages/build/cmd_factory/main.go:69 +0x4e
github.com/werf/werf/cmd/werf/common.LogRunningTime(0xc000985c38, 0x25d1f04, 0xc)
    /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/common/common.go:1388 +0x53
github.com/werf/werf/cmd/werf/stages/build/cmd_factory.NewCmdWithData.func1(0xc000142f00, 0x3fc43b8, 0x0, 0x0, 0x0, 0x0)
    /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/stages/build/cmd_factory/main.go:68 +0x1ee
github.com/spf13/cobra.(*Command).execute(0xc000142f00, 0x3fc43b8, 0x0, 0x0, 0xc000142f00, 0x3fc43b8)
    /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000dcf00, 0xc000985f30, 0x4, 0x4)
    /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
    /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
    /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/main.go:152 +0x67c
```

**Comment by n-bes** [comment]
Second call ``` DOCKER_BUILDKIT=0 werf build``` finished without problem.

**Comment by alexey-igrychev** [comment]
Fixed [here](https://github.com/werf/werf/releases/tag/v1.1.22%2Bfix23) (v1.1.22+fix23)
