### ISSUE TITLE
werf converge/render fails on helm deps with OCI-images repos

### ISSUE THREAD

**Issue by rgeraskin** [werf/werf#3415]
I use OCI-images for helm charts. With this setup `werf helm dep update .helm` works fine but later converge/render/etc fails.

Chart.yaml looks like this:
```
...
dependencies:
  - name: base-chart
    repository: "oci://registry.gitlab.com/.../helm-charts"
    version: v0.1.0
    alias: service-one
  - name: base-chart
    repository: "oci://registry.gitlab.com/.../helm-charts"
    version: v0.1.0
    alias: service-two
```

```
❯ werf converge --repo registry.gitlab.com/asd/qwe/zxc --dev -Z
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1f8948c]
 
goroutine 1 [running]:
helm.sh/helm/v3/internal/experimental/registry.(*Client).PullChart(0x0, 0xc000d477a0, 0xc000d477a0, 0x0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210323131626-a7d92a13c117/internal/experimental/registry/client.go:170 +0x18c
helm.sh/helm/v3/pkg/getter.(*OCIGetter).get(0xc000d2c960, 0xc00158d7c0, 0x49, 0xc000699e60, 0xc00158d7c0, 0x49)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210323131626-a7d92a13c117/pkg/getter/ocigetter.go:52 +0xc1
helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get(0xc000d2c960, 0xc00158d7c0, 0x49, 0xc000d476e0, 0x4, 0x4, 0xc000d2c960, 0x0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210323131626-a7d92a13c117/pkg/getter/ocigetter.go:36 +0x77
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo(0xc001ef8238, 0xc00158cd70, 0x49, 0xc00158cdba, 0x6, 0xc001dcef20, 0xad, 0x4, 0x0, 0x0, ...)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210323131626-a7d92a13c117/pkg/downloader/chart_downloader.go:99 +0x13e
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll(0xc000a4f9e0, 0xc000e32120, 0x6, 0x6, 0x0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210323131626-a7d92a13c117/pkg/downloader/manager.go:354 +0xfc8
helm.sh/helm/v3/pkg/downloader.(*Manager).Build(0xc000a4f9e0, 0xc000a4f9e0, 0x2)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210323131626-a7d92a13c117/pkg/downloader/manager.go:145 +0x3a6
github.com/werf/werf/pkg/deploy/helm/command_helpers.BuildChartDependenciesInDir(0x2e51860, 0xc0004018c0, 0xc000df00c0, 0xc00127ae70, 0x0, 0x0, 0xc001dcea50, 0xa6, 0xc0000281e0, 0x0, ...)        /home/ubuntu/actions-runner/_work/werf/werf/pkg/deploy/helm/command_helpers/build_chart_dependencies.go:65 +0x502
github.com/werf/werf/pkg/deploy/helm/chart_extender.GetPreparedChartDependenciesDir.func1(0x0, 0x0)
        /home/ubuntu/actions-runner/_work/werf/werf/pkg/deploy/helm/chart_extender/chart_dependencies_loader.go:91 +0x63b
github.com/werf/logboek/internal/stream.(*Stream).logProcess.func1(0x255f3c0, 0xc000ae7d00)
        /home/ubuntu/go/pkg/mod/github.com/werf/logboek@v0.5.3/internal/stream/process.go:150 +0x26
github.com/werf/logboek/internal/stream.(*Stream).logProcess(0xc00012c1c0, 0xc000e08300, 0x1b, 0xc000e72ae0, 0xc000721fc0, 0x23e5301, 0xc000721fc0)
        /home/ubuntu/go/pkg/mod/github.com/werf/logboek@v0.5.3/internal/stream/process.go:157 +0x135
github.com/werf/logboek/internal/stream.(*LogProcess).DoError(0xc000721ec0, 0xc000721fc0, 0x1b, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/werf/logboek@v0.5.3/internal/stream/process_types.go:201 +0xd2
github.com/werf/werf/pkg/deploy/helm/chart_extender.GetPreparedChartDependenciesDir(0x2e51860, 0xc0004018c0, 0xc000a31800, 0xc0000281e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/actions-runner/_work/werf/werf/pkg/deploy/helm/chart_extender/chart_dependencies_loader.go:76 +0x580
github.com/werf/werf/pkg/deploy/helm/chart_extender.LoadChartDependencies(0x2e51860, 0xc0004018c0, 0xc000720880, 0x7, 0x8, 0xc0000281e0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/actions-runner/_work/werf/werf/pkg/deploy/helm/chart_extender/chart_dependencies_loader.go:174 +0x5bb
github.com/werf/werf/pkg/deploy/helm/chart_extender.(*WerfChart).LoadDir(0xc0011df760, 0xc001a06ea0, 0x1e, 0xc000ae7990, 0xc0019ba858, 0x0, 0xc00009c700, 0x7f51bcf45108, 0x0)
        /home/ubuntu/actions-runner/_work/werf/werf/pkg/deploy/helm/chart_extender/werf_chart.go:201 +0x1e2
helm.sh/helm/v3/pkg/chart/loader.LoadDirWithOptions(0xc001a06ea0, 0x1e, 0x2e757c0, 0xc0011df760, 0x29a6a08, 0xc0019ba820, 0x0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210323131626-a7d92a13c117/pkg/chart/loader/directory.go:53 +0x16a
helm.sh/helm/v3/pkg/chart/loader.DirLoader.Load(...)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210323131626-a7d92a13c117/pkg/chart/loader/directory.go:41
helm.sh/helm/v3/pkg/chart/loader.LoadWithOptions(0xc001a06ea0, 0x1e, 0x2e757c0, 0xc0011df760, 0x29a6a08, 0xc0011df760, 0xc001341530, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210323131626-a7d92a13c117/pkg/chart/loader/load.go:93 +0x9a
helm.sh/helm/v3/pkg/chart/loader.Load(...)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210323131626-a7d92a13c117/pkg/chart/loader/load.go:85
helm.sh/helm/v3/cmd/helm.NewUpgradeCmd.func2(0xc0014c78c0, 0xc000d38ee0, 0x2, 0x2, 0x1e, 0xc000de1f20)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210323131626-a7d92a13c117/cmd/helm/upgrade.go:195 +0x682
github.com/werf/werf/cmd/werf/converge.run.func3(0xc000bc8a40, 0x2e51860)
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/converge/converge.go:433 +0x154
github.com/werf/werf/pkg/deploy/helm/command_helpers.LockReleaseWrapper(0x2e51860, 0xc0004018c0, 0xc000df2410, 0xf, 0xc000bc8a40, 0xc00069b618, 0x0, 0x0)
        /home/ubuntu/actions-runner/_work/werf/werf/pkg/deploy/helm/command_helpers/lock_release_wrapper.go:16 +0x121
github.com/werf/werf/cmd/werf/converge.run(0x2e51860, 0xc0004018c0, 0x2e75940, 0xc000e33470, 0x0, 0x0)
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/converge/converge.go:432 +0x1efd
github.com/werf/werf/cmd/werf/converge.runMain(0x2e51860, 0xc0005f5470, 0x0, 0x0)
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/converge/converge.go:241 +0x738
github.com/werf/werf/cmd/werf/converge.NewCmd.func1.1(0xc00ea7d530adb64b, 0x5946b52)
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/converge/converge.go:86 +0x33
github.com/werf/werf/cmd/werf/common.LogRunningTime(0xc000aa7d38, 0xc, 0xc000468d10)
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/common/common.go:1355 +0x53
github.com/werf/werf/cmd/werf/converge.NewCmd.func1(0xc0001d1340, 0xc000a54c40, 0x0, 0x4, 0x0, 0x0)
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/converge/converge.go:85 +0x170
github.com/spf13/cobra.(*Command).execute(0xc0001d1340, 0xc000a54c00, 0x4, 0x4, 0xc0001d1340, 0xc000a54c00)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d0840, 0x0, 0xc000118c30, 0x405b1f)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/main.go:66 +0x119
```

This issue could be avoided by replacing `repository: "oci://...."` with `repository: ""` in .helm/Chart.lock.

werf v1.2.10+fix17

**Comment by rgeraskin** [comment]
hi! Thanks, but I've added the `.helm/secret-values.yaml` and now it fails again. Without `.helm/secret-values.yaml` works fine.

```
❯ werf helm dep update .helm
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x22099f6]

goroutine 1 [running]:
github.com/werf/werf/pkg/deploy/secrets_manager.(*SecretsManager).GetYamlEncoder(0x0, 0x2e57920, 0xc0008275f0, 0xc000050144, 0x18, 0x0, 0x0, 0x0)
        /home/ubuntu/actions-runner/_work/werf/werf/pkg/deploy/secrets_manager/secret_manager.go:27 +0x26
github.com/werf/werf/pkg/deploy/helm/chart_extender/helpers/secrets.(*SecretsRuntimeData).DecodeAndLoadSecrets(0xc000cdaba0, 0x2e57920, 0xc0008275f0, 0xc00065f900, 0xa, 0x10, 0x0, 0x0, 0x0, 0x7ffff29d7bd6, ...)
        /home/ubuntu/actions-runner/_work/werf/werf/pkg/deploy/helm/chart_extender/helpers/secrets/secrets_runtime_data.go:31 +0x66e
github.com/werf/werf/pkg/deploy/helm/chart_extender.(*WerfChartStub).ChartLoaded(0xc000114cc0, 0xc00065f900, 0xa, 0x10, 0xa, 0x10)
        /home/ubuntu/actions-runner/_work/werf/werf/pkg/deploy/helm/chart_extender/werf_chart_stub.go:73 +0x170
helm.sh/helm/v3/pkg/chart/loader.LoadFiles(0xc00065ed80, 0xa, 0x10, 0x2e7b940, 0xc000114cc0, 0xc000664620, 0x0, 0x0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210330195046-3366eb633f7f/pkg/chart/loader/load.go:195 +0x1f6d
helm.sh/helm/v3/pkg/chart/loader.LoadDirWithOptions(0x7ffff29d7bd6, 0x5, 0x2e7b940, 0xc000114cc0, 0xc000664620, 0x0, 0xc00014dac8, 0x40c4c6)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210330195046-3366eb633f7f/pkg/chart/loader/directory.go:63 +0x107
helm.sh/helm/v3/pkg/chart/loader.LoadDir(...)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210330195046-3366eb633f7f/pkg/chart/loader/directory.go:48
helm.sh/helm/v3/pkg/downloader.(*Manager).loadChartDir(0xc0004afa70, 0x25d9a80, 0xc00061dcc0, 0xc000680000)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210330195046-3366eb633f7f/pkg/downloader/manager.go:228 +0x13a
helm.sh/helm/v3/pkg/downloader.(*Manager).Update(0xc0004afa70, 0xc0004afa70, 0x2)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210330195046-3366eb633f7f/pkg/downloader/manager.go:154 +0x40
helm.sh/helm/v3/cmd/helm.newDependencyUpdateCmd.func1(0xc000615080, 0xc00068cdc0, 0x1, 0x1, 0x0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/werf/helm/v3@v3.0.0-20210330195046-3366eb633f7f/cmd/helm/dependency_update.go:74 +0x1d1
github.com/werf/werf/cmd/werf/helm.NewCmd.func2(0xc000615080, 0xc00068cdc0, 0x1, 0x1, 0x0, 0x0)
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/helm/helm.go:162 +0x630
github.com/spf13/cobra.(*Command).execute(0xc000615080, 0xc00068cda0, 0x1, 0x1, 0xc000615080, 0xc00068cda0)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f6000, 0x0, 0xc0000cac30, 0x405b1f)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/main.go:64 +0x119
```
