### ISSUE TITLE
Install airflow with werf CrashLoopBackOff, without werf ok

### ISSUE THREAD

**Issue by patsevanton** [werf/werf#3485]
Hello! Thanks for werf!
Try install app with werf and without werf.

**Prepare**
```
git clone https://github.com/apache/airflow.git
cd airflow
git checkout 2.0.1
cd chart
kubectl create namespace airflow
helm repo add stable https://charts.helm.sh/stable/
helm dep update
```

**Install without werf**
```
helm install airflow --set webserver.defaultUser.password=password,ingress.enabled=true,ingress.hosts[0]=airflow.192.168.22.7.xip.io . --namespace airflow
NAME: airflow
LAST DEPLOYED: Tue Apr 13 13:45:24 2021
NAMESPACE: airflow
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing Airflow!

Your release is named airflow.
You can now access your dashboard(s) by following defined Ingress urls:

Airflow dashboard:     http:///
```

**Install with werf**

```
werf helm install airflow --wait --set webserver.defaultUser.password=password,ingress.enabled=true,ingress.hosts[0]=airflow.192.168.22.7.xip.io . --namespace airflow


Error: deploy/airflow-scheduler failed: po/airflow-scheduler-6b5457d89c-6bdtr container/wait-for-airflow-migrations: CrashLoopBackOff: back-off 20s restarting failed container=wait-for-airflow-migrations pod=airflow-scheduler-6b5457d89c-6bdtr_airflow(211b813d-f9ac-4e96-be5c-fb40b2bff9b9)
```

Full log

https://gist.github.com/patsevanton/ea8386d427ba41aa2980d0978de9c14a

**Comment by distorhead** [comment]
I suppose it is not ok without werf, because helm does not check resources statuses after installation terminates with successful exit code. Werf with `--wait` flag not just applies resources manifests, but also wait until all resources are ready and working well.

Actual error states that some runtime timeout in airflow-scheduler deployment has occurred:

```
│ ┌ deploy/airflow-scheduler po/airflow-scheduler-6b5457d89c-6bdtr container/wait-for-airflow-migrations logs
│ │ [2021-04-13 13:24:23,067] {<string>:35} INFO - Waiting for migrations... 60 second(s)
│ └ deploy/airflow-scheduler po/airflow-scheduler-6b5457d89c-6bdtr container/wait-for-airflow-migrations logs
│
│ ┌ deploy/airflow-webserver po/airflow-webserver-5b74d9cc6b-pfvfn container/wait-for-airflow-migrations logs
│ │ [2021-04-13 13:24:23,067] {<string>:35} INFO - Waiting for migrations... 59 second(s)
│ └ deploy/airflow-webserver po/airflow-webserver-5b74d9cc6b-pfvfn container/wait-for-airflow-migrations logs
│
│ ┌ deploy/airflow-scheduler po/airflow-scheduler-6b5457d89c-6bdtr container/wait-for-airflow-migrations logs
│ │ Traceback (most recent call last):
│ │   File "<string>", line 32, in <module>
│ │ TimeoutError: There are still unapplied migrations after 60 seconds.
│ └ deploy/airflow-scheduler po/airflow-scheduler-6b5457d89c-6bdtr container/wait-for-airflow-migrations logs
│
│ ┌ deploy/airflow-webserver po/airflow-webserver-5b74d9cc6b-pfvfn container/wait-for-airflow-migrations logs
│ │ [2021-04-13 13:24:24,069] {<string>:35} INFO - Waiting for migrations... 60 second(s)
│ │ Traceback (most recent call last):
│ │   File "<string>", line 32, in <module>
│ │ TimeoutError: There are still unapplied migrations after 60 seconds.
│ └ deploy/airflow-webserver po/airflow-webserver-5b74d9cc6b-pfvfn container/wait-for-airflow-migrations logs
```

**Comment by patsevanton** [comment]
@distorhead 
without werf work

**kubectl get all --all-namespaces**
```
NAMESPACE            NAME                                          READY   STATUS    RESTARTS   AGE
airflow              pod/airflow-nifi-0                            4/4     Running   1          96s
airflow              pod/airflow-registry-0                        1/1     Running   0          96s
airflow              pod/airflow-zookeeper-0                       1/1     Running   0          96s
airflow              pod/airflow-zookeeper-1                       1/1     Running   0          96s
airflow              pod/airflow-zookeeper-2                       1/1     Running   0          96s
container-registry   pod/registry-7cf58dcdcc-bdlbr                 1/1     Running   0          86m
ingress              pod/nginx-ingress-microk8s-controller-8nxxk   1/1     Running   0          86m
kube-system          pod/coredns-588fd544bf-29smg                  1/1     Running   0          86m
kube-system          pod/hostpath-provisioner-75fdc8fccd-vdvvf     1/1     Running   0          86m
metallb-system       pod/controller-5f98465b6b-gds8t               1/1     Running   0          86m
metallb-system       pod/speaker-x6z28                             1/1     Running   0          86m

NAMESPACE            NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)                      AGE
airflow              service/airflow-nifi                 LoadBalancer   10.152.183.118   192.168.22.7   8080:32033/TCP               96s
airflow              service/airflow-nifi-headless        ClusterIP      None             <none>         8080/TCP,6007/TCP            96s
airflow              service/airflow-registry             ClusterIP      10.152.183.172   <none>         80/TCP                       96s
airflow              service/airflow-zookeeper            ClusterIP      10.152.183.18    <none>         2181/TCP,2888/TCP,3888/TCP   96s
airflow              service/airflow-zookeeper-headless   ClusterIP      None             <none>         2181/TCP,2888/TCP,3888/TCP   96s
container-registry   service/registry                     NodePort       10.152.183.48    <none>         5000:32000/TCP               86m
default              service/kubernetes                   ClusterIP      10.152.183.1     <none>         443/TCP                      87m
kube-system          service/kube-dns                     ClusterIP      10.152.183.10    <none>         53/UDP,53/TCP,9153/TCP       86m

NAMESPACE        NAME                                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
ingress          daemonset.apps/nginx-ingress-microk8s-controller   1         1         1       1            1           <none>                        86m
metallb-system   daemonset.apps/speaker                             1         1         1       1            1           beta.kubernetes.io/os=linux   86m

NAMESPACE            NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
container-registry   deployment.apps/registry               1/1     1            1           86m
kube-system          deployment.apps/coredns                1/1     1            1           86m
kube-system          deployment.apps/hostpath-provisioner   1/1     1            1           86m
metallb-system       deployment.apps/controller             1/1     1            1           86m

NAMESPACE            NAME                                              DESIRED   CURRENT   READY   AGE
container-registry   replicaset.apps/registry-7cf58dcdcc               1         1         1       86m
kube-system          replicaset.apps/coredns-588fd544bf                1         1         1       86m
kube-system          replicaset.apps/hostpath-provisioner-75fdc8fccd   1         1         1       86m
metallb-system       replicaset.apps/controller-5f98465b6b             1         1         1       86m

NAMESPACE   NAME                                 READY   AGE
airflow     statefulset.apps/airflow-nifi        1/1     96s
airflow     statefulset.apps/airflow-registry    1/1     96s
airflow     statefulset.apps/airflow-zookeeper   3/3     96s
```

**Comment by distorhead** [comment]
Ok, then it may be a race condition, because this _application level_ error: `There are still unapplied migrations after 60 seconds` — could also occur in helm as well, but helm-install process will silently exit. Then later at some point deployment will restart failed pods and kubectl get will show "all ready" pods.

Werf also have annotations that control tracker behaviour: `werf.io/fail-mode` and `werf.io/failures-allowed-per-replica` — these could be used to adjust tracker for your application specifically: https://werf.io/documentation/v1.2/reference/deploy_annotations.html#fail-mode (for example set `werf.io/fail-mode=HopeUntilEndOfDeployProcess` for resource).

If werf exits successfully, then it is safe to assume that application is up and running. If helm exits successfully — there is no guarantee that application is up and running right now and you should use kubectl to get application state and check.

**Comment by patsevanton** [comment]
@distorhead how set `Fail mode` to command line werf?

**Comment by distorhead** [comment]
Currently there is no way to pass tracker control annotations through cli werf commands, the only way is to set these annotations in the chart resources definitions. However we are open for PRs implementing such specification of tracker annotations using cli options.

Or you could fork airflow chart repo, adjust werf behaviour with annotations so that deployment with werf works well and make PR into upstream, suggesting working airflow chart configuration for everyone.

By the way, at some point we should implement deploy-stages to solve such cases when some resource should be started or bootstrapped and ready before even creating another dependant resource. But it will also require some annotations-configuration though.

**Comment by patsevanton** [comment]
Issue in airflow https://github.com/apache/airflow/issues/15340

**Comment by patsevanton** [comment]
I added "werf.io/fail-mode": IgnoreAndContinueDeployProcess
https://github.com/patsevanton/airflow/blob/bbe84e2d5536c673bb4fd61faca435571553e933/chart/templates/webserver/webserver-deployment.yaml#L58

and run werf --timeout=10m0s helm install --wait airflow --set webserver.defaultUser.password=password,ingress.enabled=true,ingress.hosts[0]=airflow.192.168.22.7.xip.io . --namespace airflow

and get error
`Error: deploy/airflow-webserver failed: po/airflow-webserver-6fc4696d7-mwf6l container/wait-for-airflow-migrations: CrashLoopBackOff: back-off 20s restarting failed container=wait-for-airflow-migrations pod=airflow-webserver-6fc4696d7-mwf6l_airflow(56473981-29b0-4592-94e3-afb1117a34f8)`
Full log
https://gist.github.com/patsevanton/94a9cd1ead5359c33c954a6ee61ab511

History command
```
git clone https://github.com/patsevanton/airflow.git
cd airflow/chart/
helm dependency update
kubectl create namespace airflow
werf --timeout=10m0s helm install --wait airflow --set webserver.defaultUser.password=password,ingress.enabled=true,ingress.hosts[0]=airflow.192.168.22.7.xip.io . --namespace airflow 
```

**Comment by patsevanton** [comment]
**helm install airflow --set webserver.defaultUser.password=password,ingress.enabled=true,ingress.hosts[0]=airflow.192.168.22.7.xip.io . --namespace airflow**

```
NAME: airflow
LAST DEPLOYED: Wed Apr 14 04:31:15 2021
NAMESPACE: airflow
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing Airflow!

Your release is named airflow.
You can now access your dashboard(s) by following defined Ingress urls:

Airflow dashboard:     http:///
```

**kubectl get all --all-namespaces**
```
NAMESPACE            NAME                                          READY   STATUS    RESTARTS   AGE
airflow              pod/airflow-postgresql-0                      1/1     Running   0          67s
airflow              pod/airflow-scheduler-78d9ffb5ff-tb9nd        2/2     Running   0          67s
airflow              pod/airflow-statsd-675c854c4-brqnn            1/1     Running   0          67s
airflow              pod/airflow-webserver-6fc4696d7-nlz7f         1/1     Running   0          67s
container-registry   pod/registry-7cf58dcdcc-xmzrj                 1/1     Running   0          54m
ingress              pod/nginx-ingress-microk8s-controller-wjq5r   1/1     Running   0          54m
kube-system          pod/coredns-588fd544bf-clxh5                  1/1     Running   0          54m
kube-system          pod/hostpath-provisioner-75fdc8fccd-sg4wj     1/1     Running   0          54m
metallb-system       pod/controller-5f98465b6b-s5cls               1/1     Running   0          54m
metallb-system       pod/speaker-6nr8k                             1/1     Running   0          54m

NAMESPACE            NAME                                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
airflow              service/airflow-postgresql            ClusterIP   10.152.183.94    <none>        5432/TCP                 67s
airflow              service/airflow-postgresql-headless   ClusterIP   None             <none>        5432/TCP                 67s
airflow              service/airflow-statsd                ClusterIP   10.152.183.4     <none>        9125/UDP,9102/TCP        67s
airflow              service/airflow-webserver             ClusterIP   10.152.183.117   <none>        8080/TCP                 67s
container-registry   service/registry                      NodePort    10.152.183.68    <none>        5000:32000/TCP           54m
default              service/kubernetes                    ClusterIP   10.152.183.1     <none>        443/TCP                  54m
kube-system          service/kube-dns                      ClusterIP   10.152.183.10    <none>        53/UDP,53/TCP,9153/TCP   54m

NAMESPACE        NAME                                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
ingress          daemonset.apps/nginx-ingress-microk8s-controller   1         1         1       1            1           <none>                        54m
metallb-system   daemonset.apps/speaker                             1         1         1       1            1           beta.kubernetes.io/os=linux   54m

NAMESPACE            NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
airflow              deployment.apps/airflow-scheduler      1/1     1            1           67s
airflow              deployment.apps/airflow-statsd         1/1     1            1           67s
airflow              deployment.apps/airflow-webserver      1/1     1            1           67s
container-registry   deployment.apps/registry               1/1     1            1           54m
kube-system          deployment.apps/coredns                1/1     1            1           54m
kube-system          deployment.apps/hostpath-provisioner   1/1     1            1           54m
metallb-system       deployment.apps/controller             1/1     1            1           54m

NAMESPACE            NAME                                              DESIRED   CURRENT   READY   AGE
airflow              replicaset.apps/airflow-scheduler-78d9ffb5ff      1         1         1       67s
airflow              replicaset.apps/airflow-statsd-675c854c4          1         1         1       67s
airflow              replicaset.apps/airflow-webserver-6fc4696d7       1         1         1       67s
container-registry   replicaset.apps/registry-7cf58dcdcc               1         1         1       54m
kube-system          replicaset.apps/coredns-588fd544bf                1         1         1       54m
kube-system          replicaset.apps/hostpath-provisioner-75fdc8fccd   1         1         1       54m
metallb-system       replicaset.apps/controller-5f98465b6b             1         1         1       54m

NAMESPACE   NAME                                  READY   AGE
airflow     statefulset.apps/airflow-postgresql   1/1     67s
```

**Comment by distorhead** [comment]
@patsevanton `"werf.io/fail-mode": IgnoreAndContinueDeployProcess` and other annotations should be added into the toplevel controller resource spec, not into pod spec template.

Add annotations into this metadata: https://github.com/patsevanton/airflow/blob/bbe84e2d5536c673bb4fd61faca435571553e933/chart/templates/webserver/webserver-deployment.yaml#L26

instead of this: https://github.com/patsevanton/airflow/blob/bbe84e2d5536c673bb4fd61faca435571553e933/chart/templates/webserver/webserver-deployment.yaml#L58

**Comment by distorhead** [comment]
I think we should fix documentation and add clear explaination where to add werf annotations.

**Comment by kaxil** [comment]
Hi, 👋  Airflow Maintainer here

Use the chart from master branch -- apache/airflow is a mono repo and we have a different version strategy for Helm Chart. The first official version will be released early May

**Comment by ilya-lesikov** [comment]
@kaxil Thanks.

Closing this.
