### ISSUE TITLE
werf bundle export failed with stacktrace

### ISSUE THREAD

**Issue by iamalryz** [werf/werf#3651]
### Common information

**Werf version:** v1.2.12+fix2
**Application:** https://github.com/werf/quickstart-application

### Problem description

I'm trying to export a bundle with the next command: `werf bundle export --repo <repo>`. It successfully built and published images but then it failed with stacktrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2536f7a]

goroutine 1 [running]:
github.com/werf/werf/cmd/werf/bundle/export.runExport(0x307b6a8, 0xc000815dd0, 0x0, 0x0)
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/bundle/export/export.go:332 +0x1cfa
github.com/werf/werf/cmd/werf/bundle/export.NewCmd.func1.1(0xc03b91af9722fb21, 0x26c0a5a)
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/bundle/export/export.go:67 +0x33
github.com/werf/werf/cmd/werf/common.LogRunningTime(0xc00064dd48, 0xc, 0xc000421510)
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/common/common.go:1352 +0x50
github.com/werf/werf/cmd/werf/bundle/export.NewCmd.func1(0xc0008ad900, 0xc0006406e0, 0x0, 0x2, 0x0, 0x0)
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/bundle/export/export.go:66 +0x171
github.com/spf13/cobra.(*Command).execute(0xc0008ad900, 0xc000640680, 0x2, 0x2, 0xc0008ad900, 0xc000640680)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0008ac000, 0x0, 0xc0000b4ba0, 0x4063c5)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/ubuntu/actions-runner/_work/werf/werf/cmd/werf/main.go:64 +0x125
```

### Steps to reproduce

1. `git clone https://github.com/werf/quickstart-application.git`
2. `cd quickstart-application`
3. `werf bundle export --repo <repo>`

**Comment by alexey-igrychev** [comment]
fixed in v1.2.12+fix5
