### ISSUE TITLE
panic: interface conversion: cache.DeletedFinalStateUnknown is not runtime.Object: missing method DeepCopyObject

### ISSUE THREAD

**Issue by ilya-lesikov** [werf/werf#3925]
v1.1.23+fix50

Command:
```yaml
# all the options here most likely unrelated
werf deploy --stages-storage :local --timeout 21600 ...
```
... which tried to deploy a Deployment + PV + PVC + 2x Service + CM + VPA resulted in:
```
...
Status progress
panic: interface conversion: cache.DeletedFinalStateUnknown is not runtime.Object: missing method DeepCopyObject [recovered]
	panic: interface conversion: cache.DeletedFinalStateUnknown is not runtime.Object: missing method DeepCopyObject [recovered]
	panic: interface conversion: cache.DeletedFinalStateUnknown is not runtime.Object: missing method DeepCopyObject

goroutine 253 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:55 +0x105
panic(0x24c83e0, 0xc00389f6e0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:55 +0x105
panic(0x24c83e0, 0xc00389f6e0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
k8s.io/client-go/tools/watch.NewIndexerInformerWatcher.func3(0x2587e00, 0xc0021d59c0)
	/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/watch/informerwatcher.go:135 +0x9d
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/controller.go:232
k8s.io/client-go/tools/cache.newInformer.func1(0x24da900, 0xc000e11ce0, 0x1, 0xc000e11ce0)
	/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/controller.go:399 +0x360
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc00390c790, 0xc00380ce10, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/delta_fifo.go:492 +0x235
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc003920480)
	/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/controller.go:173 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0038e5f20)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000fc9f20, 0x2da3880, 0xc00380ce40, 0xc000d83601, 0xc000b0a2a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0038e5f20, 0x3b9aca00, 0x0, 0xc003934001, 0xc000b0a2a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc003920480, 0xc000b0a2a0)
	/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/controller.go:145 +0x2c4
k8s.io/client-go/tools/watch.NewIndexerInformerWatcher.func4(0xc000b0a3c0, 0xc00380ccf0, 0x2dfb6a0, 0xc003920480, 0xc000da8be0)
	/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/watch/informerwatcher.go:146 +0x8b
created by k8s.io/client-go/tools/watch.NewIndexerInformerWatcher
	/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/watch/informerwatcher.go:143 +0x3af
section_end:1636731822:step_script
ERROR: Job failed: exit status 1
```
Redeploy fixed it.

**Comment by ilya-lesikov** [comment]
Similar problem was in Deckhouse, this might be related https://github.com/deckhouse/deckhouse/blob/1e3730b181017c897f2fece2bec928d0b51d36b3/dhctl/pkg/kubernetes/client/informer.go#L109
