### ISSUE TITLE
panic while `werf build` in Gitlab CI  in docker`unexpected regexp find submatch result`

### ISSUE THREAD

**Issue by Ivanello** [werf/werf#4063]
panic while `werf build` in Gitlab CI  in docker executor
OS Ubuntu Linux 20.04 LTS
local build works ok

```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
$ werf build --parallel=false
Version: v1.2.45
Using project dir: /builds/
Using werf config render file: /tmp/werf-config-render-861396291
Getting client id for the http synchronization server
┌ Getting client id for the http synchronization server
│ Using clientID "" for http synchronization server at address                               ↵
│ https://synchronization.werf.io/
└ Getting client id for the http synchronization server (0.39 seconds)
⛵ image backend
┌ ⛵ image backend
panic: unexpected regexp find submatch result [] (0)
goroutine 1 [running]:
github.com/werf/werf/pkg/docker_registry.(*api).ParseReferenceParts(0xc00081c4a8, {0xc00093cc60, 0x85})
	/git/pkg/docker_registry/api.go:362 +0x525
github.com/werf/werf/pkg/docker_registry.(*api).GetRepoImage(0x2edad89, {0x40c607, 0xc000952ef0}, {0xc00093cc60, 0x1})
	/git/pkg/docker_registry/api.go:137 +0x18d
github.com/werf/werf/pkg/storage.(*RepoStagesStorage).GetStageDescription(0xc000c19c80, {0x33dc468, 0xc00004e510}, {0xc000c6b600, 0xd}, {0xc00094cc40, 0x18}, 0x17e58700a41)
	/git/pkg/storage/repo_stages_storage.go:270 +0x334
github.com/werf/werf/pkg/storage/manager.getStageDescription({0x33dc468, 0xc00004e510}, {0xc000c6b600, 0x203000}, {{0xc00094cc40, 0xc000c42700}, 0x4}, {0x3472f90, 0xc000c19c80}, {0x0, ...}, ...)
	/git/pkg/storage/manager/storage_manager.go:1003 +0x459
github.com/werf/werf/pkg/storage/manager.(*StorageManager).getStagesByDigestFromCache(0xc000f34000, {0x33dc468, 0xc00004e510}, {0xc000dd6288, 0x12}, {0xc00094ca00, 0x5})
	/git/pkg/storage/manager/storage_manager.go:812 +0x410
github.com/werf/werf/pkg/storage/manager.(*StorageManager).GetStagesByDigest(0xc000e305a0, {0x33dc468, 0xc00004e510}, {0xc000dd6288, 0x12}, {0xc00094ca00, 0x38})
	/git/pkg/storage/manager/storage_manager.go:736 +0x65
github.com/werf/werf/pkg/build.(*BuildPhase).calculateStage(0xc000932b00, {0x33dc468, 0xc00004e510}, 0x4eb87b, {0x345c718, 0xc000e305a0})
	/git/pkg/build/build_phase.go:588 +0x3f9
github.com/werf/werf/pkg/build.(*BuildPhase).onImageStage(0xc000932b00, {0x33dc468, 0xc00004e510}, 0xc000928580, {0x345c718, 0xc000e305a0}, 0x58)
	/git/pkg/build/build_phase.go:387 +0x28b
github.com/werf/werf/pkg/build.(*BuildPhase).OnImageStage.func1(0xc000e305a0, {0x345c718, 0xc000e305a0}, 0x20)
	/git/pkg/build/build_phase.go:362 +0x45
github.com/werf/werf/pkg/build.(*StagesIterator).OnImageStage(0xc00068b100, {0x33dc468, 0xc00004e510}, 0xc000928580, {0x345c718, 0xc000e305a0}, 0xc0013a6ca0)
	/git/pkg/build/stages_iterator.go:56 +0x332
github.com/werf/werf/pkg/build.(*BuildPhase).OnImageStage(0xc000fb0810, {0x33dc468, 0xc00004e510}, 0xc0013aecf0, {0x345c718, 0xc000e305a0})
	/git/pkg/build/build_phase.go:361 +0x65
github.com/werf/werf/pkg/build.(*Conveyor).doImage.func2()
	/git/pkg/build/conveyor.go:625 +0xa5d
github.com/werf/logboek/internal/stream.(*Stream).logProcess.func1()
	/go/pkg/mod/github.com/werf/logboek@v0.5.4/internal/stream/process.go:150 +0x1b
github.com/werf/logboek/internal/stream.(*Stream).logProcess(0xc000120078, {0xc000fb0708, 0x203000}, 0xc0013aeae0, 0xc00068afc0)
	/go/pkg/mod/github.com/werf/logboek@v0.5.4/internal/stream/process.go:157 +0x1d1
github.com/werf/logboek/internal/stream.(*LogProcess).DoError(0xc00068af80, 0xc00068afc0)
	/go/pkg/mod/github.com/werf/logboek@v0.5.4/internal/stream/process_types.go:201 +0xa5
github.com/werf/werf/pkg/build.(*Conveyor).doImage(0x636fda, {0x33dc468, 0xc00004e510}, 0xc000928580, {0xc00068e9a0, 0x1, 0x1}, 0x10)
	/git/pkg/build/conveyor.go:611 +0x1e2
github.com/werf/werf/pkg/build.(*Conveyor).doImages(0xc0003f9800, {0x33dc468, 0xc00004e510}, {0xc00068e9a0, 0x1, 0x1}, 0xc)
	/git/pkg/build/conveyor.go:545 +0x107
github.com/werf/werf/pkg/build.(*Conveyor).runPhases(0x2b42040, {0x33dc468, 0xc00004e510}, {0xc00068e9a0, 0x1, 0x1}, 0x0)
	/git/pkg/build/conveyor.go:520 +0x74
github.com/werf/werf/pkg/build.(*Conveyor).Build(0xc0003f9800, {0x33dc468, 0xc00004e510}, {{0x0, 0x0}, {{0x0, 0x0, 0x0}}, {0x0, 0x0}, ...})
	/git/pkg/build/conveyor.go:423 +0x1ff
github.com/werf/werf/cmd/werf/build.run.func1(0xc000c1b680)
	/git/cmd/werf/build/main.go:269 +0x58
github.com/werf/werf/pkg/build.(*ConveyorWithRetryWrapper).WithRetryBlock.func1()
	/git/pkg/build/conveyor_with_retry.go:63 +0x243
github.com/werf/werf/pkg/storage/manager.RetryOnStagesStorageCacheResetError({0x33dc468, 0xc00004e510}, {0x346ccb0, 0xc000f34000}, 0xc000c43550)
	/git/pkg/storage/manager/storage_manager.go:87 +0x4c
github.com/werf/werf/pkg/build.(*ConveyorWithRetryWrapper).WithRetryBlock(0xc000a4c810, {0x33dc468, 0xc00004e510}, 0x0)
	/git/pkg/build/conveyor_with_retry.go:47 +0x74
github.com/werf/werf/cmd/werf/build.run({0x33dc468, 0xc00004e510}, {0x3444b08, 0x4d742c8}, {0x342c820, 0xc000a4c810}, {0xc00047aa40, 0x0, 0x1})
	/git/cmd/werf/build/main.go:268 +0xa31
github.com/werf/werf/cmd/werf/build.runMain({0x33dc468, 0xc0003c96e0}, {0xc00047aa40, 0xc000c43c48, 0x4ca177})
	/git/cmd/werf/build/main.go:196 +0x6ac
github.com/werf/werf/cmd/werf/build.NewCmd.func1.1()
	/git/cmd/werf/build/main.go:66 +0x2d
github.com/werf/werf/cmd/werf/common.LogRunningTime(0xc000c43d68)
	/git/cmd/werf/common/common.go:1464 +0x42
github.com/werf/werf/cmd/werf/build.NewCmd.func1(0xc0001f2f00, {0xc00047aa40, 0x0, 0x1})
	/git/cmd/werf/build/main.go:65 +0x1ab
github.com/spf13/cobra.(*Command).execute(0xc0001f2f00, {0xc00047aa30, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000750000)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/git/cmd/werf/main.go:65 +0xfb
Cleaning up project directory and file based variables
```

**Comment by alexey-igrychev** [comment]
Could you provide more details by running werf in debug mode (with `--debug` option or `WERF_DEBUG=1` environment variable)?

**Comment by alexey-igrychev** [comment]
This panic is caused by using an invalid repository address as the stages storage (`--repo`/`--final-repo`/`--cache-repo`/`--secondary-repo`). Recently, someone came to us with a similar problem, and it was a slash at the end of the address (e.g. `--repo=ghcr.io/account/project/`).
