### ISSUE TITLE
Build failed with custom sync server

### ISSUE THREAD

**Issue by n-bes** [werf/werf#4309]
Sync server version: 1.2.10+fix22

Client version: 1.2.79

```

┌ Getting client id for the http synchronization server
panic: unexpected regexp find submatch result [] (0)

goroutine 1 [running]:
github.com/werf/werf/pkg/docker_registry.(*api).parseReferenceParts(0xc00118098a, {0x7ffd74419642, 0x1d})
   /git/pkg/docker_registry/api.go:366 +0x57e
github.com/werf/werf/pkg/docker_registry.(*DockerRegistryWithCache).mustGetCachedTagsID(0xc000b33c40, {0x7ffd74419642, 0x1d})
   /git/pkg/docker_registry/docker_registry_with_cache.go:147 +0x43
github.com/werf/werf/pkg/docker_registry.(*DockerRegistryWithCache).withCachedTags(0xc0002dcfa0, {0x7ffd74419642, 0x10}, 0xc001148ef0)
   /git/pkg/docker_registry/docker_registry_with_cache.go:125 +0x72
github.com/werf/werf/pkg/docker_registry.(*DockerRegistryWithCache).Tags(0xc0002dcfa0, {0x3a5df88, 0xc00108a0f0}, {0x7ffd74419642, 0x1d}, {0x0, 0x0, 0x0})
   /git/pkg/docker_registry/docker_registry_with_cache.go:31 +0x115
github.com/werf/werf/pkg/storage.(*RepoStagesStorage).GetClientIDRecords(0xc0011a8ea0, {0x3a5df88, 0xc00108a0f0}, {0xc0012f0ed0, 0x26}, {0x0, 0x0, 0x0})
   /git/pkg/storage/repo_stages_storage.go:821 +0x170
github.com/werf/werf/pkg/storage/synchronization_server.GetOrCreateClientID({0x3a5df88, 0xc00108a0f0}, {0xc0012f0ed0, 0x26}, 0x46ca33, {0x3b06578, 0xc0011a8ea0})
   /git/pkg/storage/synchronization_server/client_id.go:13 +0x8b
github.com/werf/werf/cmd/werf/common.GetSynchronization.func2.1()
   /git/cmd/werf/common/synchronization.go:137 +0xea
github.com/werf/logboek/internal/stream.(*Stream).logProcess.func1()
   /go/pkg/mod/github.com/werf/logboek@v0.5.4/internal/stream/process.go:150 +0x1b
github.com/werf/logboek/internal/stream.(*Stream).logProcess(0xc00000e078, {0xc000b33c00, 0x35}, 0xc0011a8ed0, 0xc000116be0)
   /go/pkg/mod/github.com/werf/logboek@v0.5.4/internal/stream/process.go:157 +0x1d1
github.com/werf/logboek/internal/stream.(*LogProcess).DoError(0xc0009a1280, 0xc000116be0)
   /go/pkg/mod/github.com/werf/logboek@v0.5.4/internal/stream/process_types.go:201 +0xa5
github.com/werf/werf/cmd/werf/common.GetSynchronization.func2({0x7ffd744196b3, 0x1f}, {0x3b06578, 0xc0011a8ea0})
   /git/cmd/werf/common/synchronization.go:136 +0x1f8
github.com/werf/werf/cmd/werf/common.GetSynchronization({0x3a5df88, 0xc00108a0f0}, 0x56755c0, {0xc0012f0ed0, 0x56755c0}, {0x3b06578, 0xc0011a8ea0})
   /git/cmd/werf/common/synchronization.go:164 +0x1f4
github.com/werf/werf/cmd/werf/build.run({0x3a5df88, 0xc00108a0f0}, {0x3ad1ab8, 0x56be5a0}, {0x3ab70f0, 0xc0011d1320}, {0xc00035eb90, 0x1, 0x5})
   /git/cmd/werf/build/main.go:227 +0x34a
github.com/werf/werf/cmd/werf/build.runMain({0x3a5df88, 0xc000dcf4a0}, {0xc00035eb90, 0xc0009ffc48, 0x4d0557})
   /git/cmd/werf/build/main.go:195 +0x6cc
github.com/werf/werf/cmd/werf/build.NewCmd.func1.1()
   /git/cmd/werf/build/main.go:65 +0x2d
github.com/werf/werf/cmd/werf/common.LogRunningTime(0xc0009ffd68)
   /git/cmd/werf/common/common.go:1492 +0x42
github.com/werf/werf/cmd/werf/build.NewCmd.func1(0xc0003fca00, {0xc00035eb90, 0x1, 0x5})
   /git/cmd/werf/build/main.go:64 +0x1ab
github.com/spf13/cobra.(*Command).execute(0xc0003fca00, {0xc00035eb40, 0x5, 0x5})
   /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00061e500)
   /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
   /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
   /git/cmd/werf/main.go:71 +0xfb
```

**Comment by alexey-igrychev** [comment]
dup https://github.com/werf/werf/issues/4063
