### ISSUE TITLE
Panic building multi-platform images

### ISSUE THREAD

**Issue by jarojasm95** [werf/werf#6315]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

2.9.1

### How to reproduce

I haven't bee able to reproduce consistently but given the stack trace it seems specific to multiplatform images and rebuilding.

This seems related to this change https://github.com/werf/werf/pull/5618/files#diff-ea9b317bcabdca97716079f76aa2a660f8097031e01d4798ee5bb6e7dd3cb231R483

It seems that previously it could return an empty list which would avoid the null pointer exception, now it always expects a value even though `GetMultiplatformImage` can potentially return `null`

### Result

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x34575d5]

goroutine 1 [running]:
github.com/werf/werf/v2/pkg/build.(*BuildPhase).createReport(0xc000bfa6e0, {0x50b83f0, 0xc000c96330})
        /git/pkg/build/build_phase.go:493 +0xbf5
github.com/werf/werf/v2/pkg/build.(*BuildPhase).AfterImages(0xc000bfa6e0, {0x50b83f0, 0xc000c96330})
        /git/pkg/build/build_phase.go:300 +0x2c5
github.com/werf/werf/v2/pkg/build.(*Conveyor).runPhases.func1()
        /git/pkg/build/conveyor.go:586 +0x30
github.com/werf/logboek/internal/stream.(*LogProcess).DoError(0xc000fe2440, 0xc0015a53c0)
        /go/pkg/mod/github.com/werf/logboek@v0.6.1/internal/stream/process_types.go:195 +0xbb
github.com/werf/werf/v2/pkg/build.(*Conveyor).runPhases(0xc000cbe6e0?, {0x50b83f0?, 0xc000c96330}, {0xc001582610, 0x1, 0x1}, 0x0?)
        /git/pkg/build/conveyor.go:585 +0x47f
github.com/werf/werf/v2/pkg/build.(*Conveyor).Build(0xc000cbe6e0, {0x50b83f0, 0xc000c96330}, {{{0x0, 0x0}, 0x0, 0x0}, {{0x0, 0x0, 0x0}}, ...})
        /git/pkg/build/conveyor.go:539 +0x25e
github.com/werf/werf/v2/cmd/werf/export.run.func2(0xc000cbe6e0)
        /git/cmd/werf/export/export.go:277 +0x19a
github.com/werf/werf/v2/cmd/werf/export.run.(*ConveyorWithRetryWrapper).WithRetryBlock.func3()
        /git/pkg/build/conveyor_with_retry.go:60 +0x1e8
github.com/werf/werf/v2/pkg/storage/manager.RetryOnUnexpectedStagesStorageState({0x0?, 0x0?}, {0x0?, 0x0?}, 0xc0019877b0)
        /git/pkg/storage/manager/storage_manager.go:110 +0x22
github.com/werf/werf/v2/pkg/build.(*ConveyorWithRetryWrapper).WithRetryBlock(...)
        /git/pkg/build/conveyor_with_retry.go:45
github.com/werf/werf/v2/cmd/werf/export.run({0x50b83f0, 0xc00110e5d0}, {{0x0, 0x0, 0x0}, 0x0}, {0xc000b614f0, 0x1, 0x1}, 0xc001496ba0)
        /git/cmd/werf/export/export.go:264 +0xfda
github.com/werf/werf/v2/cmd/werf/export.NewExportCmd.func1(0xc0010cd200, {0xc000ba8640, 0x0, 0x4})
        /git/cmd/werf/export/export.go:85 +0x22e
github.com/werf/werf/v2/cmd/werf/root.SetupTelemetryInit.func1(0xc001122900?, {0xc000ba8640, 0x0, 0x4})
        /git/cmd/werf/root/root.go:248 +0xcb
github.com/spf13/cobra.(*Command).execute(0xc0010cd200, {0xc000ba8600, 0x4, 0x4})
        /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ef0900)
        /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /git/cmd/werf/main.go:45 +0x14f
```

### Expected result

Successful image build & export

**Comment by jarojasm95** [comment]
I think this may be related to running `werf build` and then `werf export`
