### ISSUE TITLE
Archive type can be empty/unknown on patch stage

### ISSUE THREAD

**Issue by distorhead** [werf/werf#965]
Build image with empty archive. Then add files to repo, make commit, rebuild.

```
$ dapp dimg build
nameless: calculating stages signatures                                                                                  [RUNNING]
Using commit `da39f46bc593e30e23c17ce740cd3333f2cb9ee4` of repo `own`
  Repository `own`: latest commit `da39f46bc593e30e23c17ce740cd3333f2cb9ee4` to `/app`
nameless: calculating stages signatures                                                                                       [OK] 0.55 sec
From                                                                                                                 [USING CACHE]
  signature: dimgstage-ex-dapp-stage-deps:41772c141b158349804ad27b354247df8984ead077a5dd601f3940536ebe9a11
  date: 2018-10-08 19:58:38 +0300
  size: 113.913 MB
Git artifacts: create archive                                                                                        [USING CACHE]
  signature: dimgstage-ex-dapp-stage-deps:d1aa6029faae81733618867c217c9e0e9d70e56ab1fc2554e790d9b14f16b96c
  date: 2018-10-08 19:58:39 +0300
  difference: 0.0 MB
HELO archiveType="" isEmpty=false
Running time 1.88 seconds
Stacktrace dumped to /tmp/dapp-stacktrace-cd19dcff-3c07-442f-ba10-959b381502d6.out
bundler: failed to load command: dapp (github.com/flant/dapp/.vendor/ruby/2.2.0/bin/dapp)
RuntimeError: unknown archive type ``
  github.com/flant/dapp/lib/dapp/dimg/git_artifact.rb:260:in `apply_patch_command'
  github.com/flant/dapp/lib/dapp/dimg/build/stage/ga_base.rb:14:in `block (2 levels) in prepare_image'
  github.com/flant/dapp/lib/dapp/dimg/build/stage/ga_base.rb:12:in `each'
  github.com/flant/dapp/lib/dapp/dimg/build/stage/ga_base.rb:12:in `block in prepare_image'
  github.com/flant/dapp/lib/dapp/dimg/build/stage/base.rb:124:in `prepare_image'
  github.com/flant/dapp/lib/dapp/dimg/build/stage/ga_base.rb:7:in `prepare_image'
  github.com/flant/dapp/lib/dapp/dimg/build/stage/base.rb:263:in `image_build'
  github.com/flant/dapp/lib/dapp/dimg/build/stage/base.rb:89:in `build!'
  github.com/flant/dapp/lib/dapp/dimg/build/stage/base.rb:87:in `build!'
```

**Comment by distorhead** [comment]
The issue is still actual with the werf when using `includePaths`:

![image](https://user-images.githubusercontent.com/1161992/76290392-33c2ce80-62bc-11ea-9ab1-4d5650b8a0f9.png)
![image](https://user-images.githubusercontent.com/1161992/76290398-36252880-62bc-11ea-868c-ac3751aef53f.png)

**Comment by alexey-igrychev** [comment]
resolved
